version: '3'

services:
  regForm:
    image: nginx:latest
    build: ./src
    volumes:
      - ./src:/usr/share/nginx/html
      
    ports:
      - 5001:80

  web:
    image: nginx:latest
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "8080:80"
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./src:/src



    #   depends_on:
    #   - postgres
    # command: ["bin/wait-for-db.sh", "java", "-jar", "/SpringBootExample.jar"]
